### ISSUE TITLE
[kartik-v/yii2-icons] CSS are not Included

### ISSUE THREAD

**Issue by abc4IT** [kartik-v/yii2-icons#11]
Dear kartik,

i have installed your icon extension successfully without any error. When i take a look on the Code, i see that the class fa etc. are not existing (How it looks: &lt;i class="fa-stack-1x fa fa-square-o"&gt;&lt;/i&gt;). So the problem is that the stylesheets are not included (only site.css and bootstrap.css).

How do i fix this now?

Best regards
Sascha

**Comment by kartik-v** [comment]
Please read the documentation thoroughly before you start using any of my extensions OR submit a query here. You need to read [through the yii2-icons documentation](http://demos.krajee.com/icons) to load the icon CSS / assets. You need to also look at how you can [use Icon::map](http://demos.krajee.com/icon-details/icon-map) before you use [use Icon::show](http://demos.krajee.com/icon-details/icon-show) and how you can set it up globally through Yii params.

**Comment by abc4IT** [comment]
I got it, i just skiped the initializing part and didn't saw that it was so important.

Thank you
