### ISSUE TITLE
Fix bug display FontAwesome at mobile

### ISSUE THREAD

**Issue by bupy7** [kartik-v/yii2-icons#14]
Hi! Please, update Font Awesome icons. Now icons not display at mobile devices.

This is fix problem:
https://github.com/tatygrassini/Font-Awesome/commit/7bef335b6e8eaadd9374552d188ef4a7fda43847
and issue
https://github.com/FortAwesome/Font-Awesome/issues/247

Thanks!

**Comment by kartik-v** [comment]
FontAwesome assets are directly installed using composer. You may want to override these CSS from AssetManager for your case.
