### ISSUE TITLE
Problem loading local mapping

### ISSUE THREAD

**Issue by devleaks** [kartik-v/yii2-icons#18]
Hello,

In the head of a view, I
Icon::map($this, Icon::WHHG);
and still get
The 'icon-framework' option has not been setup in Yii params. Check your configuration file.

If I add 'icon-framework' => 'fa' in params.php file, error disappear but Icon::show('podium-winner') (specific WHHG icon) does not show anything because 'fa' still selected, in spite of Icon::map($this, Icon::WHHG).

Works OK if I use global 'icon-framework' => 'whhg' in params.
Works OK if I use Icon::show('podium-winner', [], Icon::WHHG).

Thank you.

P.

**Comment by kartik-v** [comment]
`Icon::map` is a shortcut to loads the assets (CSS) for the relevant Icon on the page - it does not set the framework.

You must use `Icon::show` to mention what icon you render and with what framework i.e. `Icon::show('podium-winner', [], Icon::WHHG)` as you said.

If you do not provide a framework in `Icon::show` then it will read it from the `icon-framework` in `params`
