### ISSUE TITLE
Stacking icon + badge/label

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-icons#21]
Would it be possible to extend the showStack method (or add a new one) to allow stacking a bootstrap badge or at least a simple label (for example a number) over an icon?

We would be able to achieve something like [this](http://www.bootply.com/7teIvGLIzY) with either a configurable offset or at the very least just centered.

**Comment by kartik-v** [comment]
Check the [icon layers feature](http://demos.krajee.com/icons#icon-show-layers) with the new release.
