### ISSUE TITLE
Inline Displaying

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-icons#26]
The following code shows nothing:
```
Icon::map($this, Icon::UNI);
echo Icon::show('spades',[], Icon::UNI) ." UNI spades<BR>";
```

The following code does show the correct icon:
```
Icon::map($this, Icon::UNI);
echo Icon::show('spades',[], Icon::UNI) ." UNI spades<BR>";
```
I assume that the second parameter overwrites the default settings, or am I overlooking something ?

**Comment by kartik-v** [comment]
I see no difference in both the codes... what is the issue?

**Comment by robov** [comment]
Wierd... I am no longer able to reproduce the thing I was able to see before... ... sorry about this
