### ISSUE TITLE
Icons no longer working

### ISSUE THREAD

**Issue by derekisbusy** [kartik-v/yii2-icons#40]
Many of the icons no longer work..

http://demosbs3.krajee.com/icon-details/icon-show

**Comment by pavlinter** [comment]
+1

**Comment by olleharstedt** [comment]
After running

    $ php composer.phar require kartik-v/yii2-icons "@dev"

I get

    [ErrorException]                                                                         
    Undefined property: Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository::$verbose

**Comment by olleharstedt** [comment]
Oops, disregard, could be fixed with

    $ php composer.phar global require fxp/composer-asset-plugin --no-plugins
