### ISSUE TITLE
Support for Font Awesome duotone and any other Font Awesome Pro icons

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-icons#41]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-icons.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/icons).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Include support for Font Awesome Duotone icons

## Expected behavior and actual behavior

Add support for Icon::FAD

**Comment by kartik-v** [comment]
Can you please share a PR?
