### ISSUE TITLE
CDN issues - cdn.bootcss.com - ping loss

### ISSUE THREAD

**Issue by TonisOrmisson** [kartik-v/yii2-icons#47]
The CDN currently has issues from a range of locations 
![image](https://user-images.githubusercontent.com/6357451/113997772-21b9b380-9861-11eb-863b-e4bc4abab99f.png)

The average ping latency seems to be huge and also package loss in some locations. Have not had the time to go into details, but maybe its a good idea to reconsider the CDN provider. And have an option to easily override the asset CDN provider via config.

**Comment by kartik-v** [comment]
Hi bootcss.com is not used any more in this package. You may want to update to the latest release to ensure you have the correct updated package release.

Secondly, you can always override all these assets (and the CSS/JS locations) using [Yii2 Asset Manager](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#example).

**Comment by TonisOrmisson** [comment]
Indeed, thanks. Sry for not checking the obvious :)
